import com.ncorti.ktfmt.gradle.TrailingCommaManagementStrategy

plugins {
    alias(libs.plugins.benmanesVersions)
    alias(libs.plugins.detekt)
    alias(libs.plugins.kapt)
    alias(libs.plugins.kotlin)
    alias(libs.plugins.kotlinSpring)
    alias(libs.plugins.ktfmt)
    alias(libs.plugins.springBoot)
    alias(libs.plugins.springBootDependencies)
}

group = 'com.damianryan'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

kotlin {
    compilerOptions {
        progressiveMode = true
        extraWarnings = true
    }
}

repositories {
    mavenCentral()
}

dependencies {
    annotationProcessor libs.springBoot.configurationProcessor

    implementation libs.springBoot.starter.restclient
    implementation libs.jackson.module.kotlin
    implementation libs.threeten.extra

    developmentOnly libs.springBoot.devtools

    testImplementation libs.springBoot.starter.test
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
}

ktfmt {
    kotlinLangStyle()
    maxWidth.set(120)
    blockIndent.set(4)
    continuationIndent.set(4)
    removeUnusedImports.set(true)
    trailingCommaManagementStrategy.set(TrailingCommaManagementStrategy.NONE)
}

test {
    useJUnitPlatform()
}

bootRun.doFirst {
    systemProperty "octopus.account-number", System.getProperty("octopus.account-number")
    systemProperty "octopus.api-key", System.getProperty("octopus.api-key")
    systemProperty "octopus.electricity-product-code", System.getProperty("octopus.electricity-product-code")
    systemProperty "octopus.electricity-region", System.getProperty("octopus.electricity-region")
    systemProperty "octopus.arrangement-date", System.getProperty("octopus.arrangement-date")
    systemProperty "octopus.period-from", System.getProperty("octopus.period-from")
}