spring:
  application:
    name: octopus-client
  main:
    banner-mode: off
    keep-alive: true
    lazy-initialization: true
  threads:
    virtual:
      enabled: true

logging:
  level:
    web: info

octopus:
  base-url: https://api.octopus.energy/v1

rest-client:
  logging:
    enabled: true
    headers: off
