[versions]
# plugins
ben-manes-versions = "0.58.0"
detekt = "2.0.0-alpha.5"
ktfmt = "0.27.0"
kotlin = "2.4.0"
spring-boot = "4.1.0"
spring-dependency-management = "1.1.7"

# libraries
jackson = "3.2.1"
threeten = "1.10.0"

[libraries]
# libraries with unmanaged versions
threeten-extra = { module = "org.threeten:threeten-extra", version.ref = "threeten" }

# libraries whose versions are typically managed but which are constrained due to CVEs
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }

# libraries with managed versions
caffeine = { module = "com.github.ben-manes.caffeine:caffeine" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }
micrometer-tracing-bridge-brave = { module = "io.micrometer:micrometer-tracing-bridge-brave" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }
spring-boot-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache" }
spring-boot-starter-restclient = { module = "org.springframework.boot:spring-boot-starter-restclient" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }

[plugins]
benmanes-versions = { id = "io.github.ben-manes.versions", version.ref = "ben-manes-versions" }
detekt = { id = "dev.detekt", version.ref = "detekt" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-boot-dependencies = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
